version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5433:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/var/lib/postgresql/csvs

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_TYPE: postgres
      MB_DB_PORT: 5432
      MB_DB_DBNAME: mydb
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data:
